### ISSUE TITLE
No module named 'domains' on "Play all/Play unwatched"

### ISSUE THREAD

**Issue by elbowz** [gedisony/plugin.video.reddit_viewer#6]
Kodi v19.0.0 Git:20210304-nogitfound
Platform: Linux x86 64-bit, Arch Linux rolling, kernel: Linux x86 64-bit version 5.11.11-arch1-1

```
2021-04-08 14:03:10.694 T:11052   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'domains'
                                                   Traceback (most recent call last):
                                                     File "/home/muttley/.kodi/addons/plugin.video.reddit_viewer/default.py", line 170, in <module>
                                                       plugin_modes[mode](url,name,type_)
                                                     File "/home/muttley/.kodi/addons/plugin.video.reddit_viewer/resources/lib/autoplay.py", line 74, in autoPlay
                                                       from domains import sitesBase, parse_reddit_link, build_DirectoryItem_url_based_on_media_type
                                                   ModuleNotFoundError: No module named 'domains'
                                                   -->End of Python script error report<--
```

Great addon, Thanks!!

p.s. why is it not pushed on official kodi repo?

**Comment by gedisony** [comment]
hi elbowz, Thanks for letting me know. 
I verify that the error exists and made corrections. 
But there seems to be another problem with - Play All  
Kodi freezes. I don't know if it happens with other OS. 
I could not figure out how to get a different method working. 
Workaround is to use context menu > Play from here

as for why it is not pushed into the kodi repo:
The addon lets you download the latest youtube_dl
Any addon that downloads code to modify itself is against kodi rules and I do not want to remove the feature. 
Also, I'm lazy.

**Comment by elbowz** [comment]
> hi elbowz, Thanks for letting me know.
> I verify that the error exists and made corrections.
> But there seems to be another problem with - Play All
> Kodi freezes. I don't know if it happens with other OS.
> I could not figure out how to get a different method working.
> Workaround is to use context menu > Play from here

Thank for the fix and the workaround...but now nothing work anymore :(
```
2021-04-17 11:45:00.108 T:10674   DEBUG <general>: reddit_viewer MainThread:error getting ytdl local version:No module named 'resources.lib.youtube_dl'
2021-04-17 11:45:00.108 T:10674   DEBUG <general>: reddit_viewer MainThread:playYTDLVideo Exception:<class 'AttributeError'>  'xbmcout' object has no attribute 'isatty'
2021-04-17 11:45:00.108 T:10674   DEBUG <general>: reddit_viewer MainThread:User notification: Youtube_dl v0.0: 'xbmcout' object has no attribute 'isatty'
2021-04-17 11:45:00.108 T:10674   DEBUG <general>: reddit_viewer MainThread:   trying urlresolver...
2021-04-17 11:45:00.113 T:10674   DEBUG <general>: reddit_viewer MainThread:User notification: URLresolver: No module named 'urlresolver'
```
full log there: https://pastebin.com/CHXqc5J0

I have also try to uninstall, downgrade, without success...maybe something strange on my platform

> as for why it is not pushed into the kodi repo:
> The addon lets you download the latest youtube_dl
> Any addon that downloads code to modify itself is against kodi rules and I do not want to remove the feature.

for curiosity, but don't you sue the https://github.com/ruuk/script.module.youtube.dl, present in the official kodi repo? what else?

> Also, I'm lazy.

I perfectly and deeply understand :)
